#!/bin/bash
# List of tags ("git tag" to get a full list):
# v1.6.7
# v1.6.9
cd libretro-super
cd retroarch

# --- Switch to master HEAD ---
# git checkout master

# --- Or switch to a specific release tag ---
git checkout tags/v1.6.9

# --- Build ---
cd ..
./retroarch-build.sh
cd ..
