#!/bin/bash
#

# Load paths configuration
source path_configuration

# --- Copy default config and modify it to match installation ---
echo "Copying Retroarch default config file..."
# Never overwrite config it already exists!
if [ -f ${RETROARCH_CFG} ]; then
  echo "Configuration file ${RETROARCH_CFG} exists."
  echo "Aborting."
  exit 1
fi
cp ./libretro-super/retroarch/retroarch.cfg ${RETROARCH_CFG}

# --- General configuration ---
sed -i -e "s/# libretro_path = \"\/path\/to\/libretro.so\"/libretro_path = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# libretro_directory =/libretro_directory = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# libretro_info_path =/libretro_info_path = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# rgui_browser_directory =/rgui_browser_directory = \"~\/Games\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# core_assets_directory =/core_assets_directory = \"~\/Games\/\"/" ${RETROARCH_CFG}

# --- Directory configuration ---
sed -i -e "s/# video_shader_dir =/video_shader_dir = \"~\/bin\/retroarch\/common-shaders\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# overlay_directory =/overlay_directory = \"~\/bin\/retroarch\/overlays\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# osk_overlay_directory =/osk_overlay_directory = \"~\/bin\/retroarch\/overlays\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# assets_directory =/assets_directory = \"~\/bin\/retroarch\/assets\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# joypad_autoconfig_dir =/joypad_autoconfig_dir = \"~\/bin\/retroarch\/joy_autoconfig\/\"/" ${RETROARCH_CFG}

sed -i -e "s/# playlist_directory =/playlist_directory = \"~\/bin\/retroarch\/playlists\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# savefile_directory =/savefile_directory = \"~\/bin\/retroarch\/savefiles\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# savestate_directory =/savestate_directory = \"~\/bin\/retroarch\/savestates\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# system_directory =/system_directory = \"~\/bin\/retroarch\/system\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# screenshot_directory =/screenshot_directory = \"~\/bin\/retroarch\/screenshots\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# boxarts_directory =/boxarts_directory = \"~\/bin\/retroarch\/boxarts\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# input_remapping_directory =/input_remapping_directory = \"~\/bin\/retroarch\/remappings\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_filter_dir =/video_filter_dir = \"~\/bin\/retroarch\/video_filters\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# audio_filter_dir =/audio_filter_dir = \"~\/bin\/retroarch\/audio_filters\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# dynamic_wallpapers_directory =/dynamic_wallpapers_directory = \"~\/bin\/retroarch\/wallpapers\/\"/" ${RETROARCH_CFG}

# --- Directories already created ---
sed -i -e "s/# content_database_path =/content_database_path = \"~\/bin\/retroarch\/libretrodb\/rdb\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# cheat_database_path =/cheat_database_path = \"~\/bin\/retroarch\/libretrodb\/cht\/\"/" ${RETROARCH_CFG}
echo "cursor_directory = \"~/bin/retroarch/libretrodb/cursors/\"" >> ${RETROARCH_CFG}

# --- Other options ---
# sed -i -e "s/# menu_driver = \"rgui\"/menu_driver = \"xmb\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_font_path =/video_font_path =\"~\/bin\/retroarch\/assets\/xmb\/monochrome\/font.ttf\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_font_size = 48/video_font_size = 22/" ${RETROARCH_CFG}
sed -i -e "s/# input_max_users = 16/input_max_users = 2/" ${RETROARCH_CFG}
sed -i -e "s/# input_autodetect_enable = true/input_autodetect_enable = true/" ${RETROARCH_CFG}

# --- Extra options from Lakka (maybe added in the future) ---
# sed -i -e "s/# rgui_show_start_screen = true/rgui_show_start_screen = false/" ${RETROARCH_CFG}

# sed -i -e "s/# video_fullscreen = false/video_fullscreen = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_smooth = true/video_smooth = false/" ${RETROARCH_CFG}
# sed -i -e "s/# video_aspect_ratio_auto = false/video_aspect_ratio_auto = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_threaded = false/video_threaded = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_gpu_screenshot = true/video_gpu_screenshot = false/" ${RETROARCH_CFG}

# sed -i -e "s/# audio_driver =/audio_driver = \"alsathread\"/" ${RETROARCH_CFG}
# sed -i -e "s/# input_driver = sdl/input_driver = udev/" ${RETROARCH_CFG}
# sed -i -e "s/# input_menu_toggle_gamepad_combo =/input_menu_toggle_gamepad_combo = \"2\"/" ${RETROARCH_CFG}

# sed -i -e "s/# menu_core_enable = true/menu_core_enable = false/" ${RETROARCH_CFG}

# echo "playlist_names = \"$RA_PLAYLIST_NAMES\"" >> ${RETROARCH_CFG}
# echo "playlist_cores = \"$RA_PLAYLIST_CORES\"" >> ${RETROARCH_CFG}
