#!/bin/bash
#
# Officially recomended in
# apt install make git-core curl g++ pkg-config \
#             libglu1-mesa-dev libgbm-dev freeglut3-dev mesa-common-dev libgles2-mesa-dev \
#             libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev \
#             libxml2-dev libusb-dev \
#             nvidia-cg-toolkit
apt-get install make git-core curl g++ pkg-config \
                libglu1-mesa-dev libgbm-dev freeglut3-dev mesa-common-dev libgles2-mesa-dev \
                libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev \
                libxml2-dev libusb-dev \
                nvidia-cg-toolkit
