#!/bin/bash
#

# Load paths configuration
source path_configuration

# --- Install LibRetro cores and info files ---
echo "Creating RetroArch stuff path..."
mkdir -p ${PATH_RETROARCH_STUFF}

# Clean the cores before copying.
echo "Cleaning old LibRetro cores..."
mkdir -p ${PATH_LIBRETRO}
rm -f ${PATH_LIBRETRO}/*.so

echo "Installing LibRetro cores..."
cp ./libretro-super/dist/unix/*.so ${PATH_LIBRETRO}

echo "Installing LibRetro core info files..."
mkdir -p ${PATH_RETROARCH_STUFF}/info/
rm -f ${PATH_RETROARCH_STUFF}/info/*.info
cp ./libretro-super/dist/info/*.info ${PATH_RETROARCH_STUFF}/info/

# --- Install Retroarch ---
# Based on Lakka retroarch installation script
# Have a look at https://github.com/libretro/Lakka/blob/lakka/packages/libretro/retroarch/package.mk
echo "Installing Retroarch binary..."
mkdir -p ${PATH_RETROARCH_BIN}
cp ./libretro-super/retroarch/retroarch ${PATH_RETROARCH_BIN}

# --- Create RetroArch paths ---
# See https://github.com/libretro/RetroArch/blob/master/fetch-submodules.sh
echo "Creating RetroArch stuff paths..."
mkdir -p ${PATH_RETROARCH_STUFF}/shaders_cg/ # common-shaders (option video_shader_dir)
mkdir -p ${PATH_RETROARCH_STUFF}/overlays/   # common-overlays (option overlay_directory)
mkdir -p ${PATH_RETROARCH_STUFF}/assets/     # retroarch-assets (option assets_directory)
mkdir -p ${PATH_RETROARCH_STUFF}/autoconfig/ # retroarch-joypad-autoconfig (option joypad_autoconfig_dir)
mkdir -p ${PATH_RETROARCH_STUFF}/libretrodb/ # libretro-database (option content_database_path)

# --- Create other directories that will be needed later ---
mkdir -p ${PATH_RETROARCH_STUFF}/playlists/     # Option playlist_directory, default playlists
mkdir -p ${PATH_RETROARCH_STUFF}/savefiles/     # Option savefile_directory, default savefiles
mkdir -p ${PATH_RETROARCH_STUFF}/savestates/    # Option savestate_directory, default savestates
mkdir -p ${PATH_RETROARCH_STUFF}/system/        # Option system_directory, default system
mkdir -p ${PATH_RETROARCH_STUFF}/screenshots/   # Option screenshot_directory, default screenshots
mkdir -p ${PATH_RETROARCH_STUFF}/boxarts/       # Option boxarts_directory, default boxarts
mkdir -p ${PATH_RETROARCH_STUFF}/remappings/    # Option input_remapping_directory
mkdir -p ${PATH_RETROARCH_STUFF}/video_filters/ # Option video_filter_dir
mkdir -p ${PATH_RETROARCH_STUFF}/audio_filters/ # Option audio_filter_dir
mkdir -p ${PATH_RETROARCH_STUFF}/wallpapers/    # Option dynamic_wallpapers_directory

# --- Copy Retroarch stuff (assets, databases, etc.) ---
echo "Installing shaders_cg ..."
cp -r ./libretro-super/retroarch/media/shaders_cg/* ${PATH_RETROARCH_STUFF}/shaders_cg/

echo "Installing overlays ..."
cp -r ./libretro-super/retroarch/media/overlays/* ${PATH_RETROARCH_STUFF}/overlays/

echo "Installing assets ..."
cp -r ./libretro-super/retroarch/media/assets/* ${PATH_RETROARCH_STUFF}/assets/

echo "Installing joystick autoconfig ..."
cp -r ./libretro-super/retroarch/media/autoconfig/* ${PATH_RETROARCH_STUFF}/autoconfig/

echo "Installing libretrodb ..."
cp -r ./libretro-super/retroarch/media/libretrodb/* ${PATH_RETROARCH_STUFF}/libretrodb

# --- Installing core specific stuff ---
echo "Installing core-specific stuff..."
# Copy PPSSPP assets if PPSSPP core compiled
# See http://wiki.libretro.com/index.php?title=PPSSPP

echo "Done"
exit 0
