#!/bin/bash
#

# Load paths configuration
source path_configuration

# --- Install LibRetro cores and info files ---
# Clean the cores before copying.
echo "Cleaning old LibRetro cores..."
mkdir -p ${PATH_LIBRETRO}
rm -f ${PATH_LIBRETRO}/*.so

echo "Installing LibRetro cores..."

cd libretro-super
bash libretro-install.sh ${INSTALL_PATH_LIBRETRO}
cd ..

# --- Install Retroarch ---
# * Based on Lakka retroarch installation script
# * Have a look at https://github.com/libretro/Lakka/blob/lakka/packages/libretro/retroarch/package.mk
echo "Copying Retroarch files..."
mkdir -p ${INSTALL_PATH_RETROARCH}
cp ./libretro-super/retroarch/retroarch ${INSTALL_PATH_RETROARCH}

# --- Copy Retroarch stuff ---
# See https://github.com/libretro/RetroArch/blob/master/fetch-submodules.sh
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}

# common-shaders (option video_shader_dir)
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/common-shaders
cp -r ./libretro-super/retroarch/media/shaders_cg/* ${INSTALL_PATH_RETROARCH_STUFF}/common-shaders

# common-overlays (option overlay_directory)
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/overlays
cp -r ./libretro-super/retroarch/media/overlays/* ${INSTALL_PATH_RETROARCH_STUFF}/overlays

# retroarch-assets (option assets_directory)
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/assets
cp -r ./libretro-super/retroarch/media/assets/* ${INSTALL_PATH_RETROARCH_STUFF}/assets

# retroarch-joypad-autoconfig (option joypad_autoconfig_dir)
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/joy_autoconfig
cp -r ./libretro-super/retroarch/media/autoconfig/* ${INSTALL_PATH_RETROARCH_STUFF}/joy_autoconfig

# libretro-database (option content_database_path)
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/libretrodb
cp -r ./libretro-super/retroarch/media/libretrodb/* ${INSTALL_PATH_RETROARCH_STUFF}/libretrodb

# * Create other directories that will be needed later
# option playlist_directory, default playlists
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/playlists/

# Option savefile_directory, default savefiles
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/savefiles/

# Option savestate_directory, default savestates
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/savestates/

# Option system_directory, default system
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/system/

# Option screenshot_directory, default screenshots
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/screenshots/

# Option boxarts_directory, default boxarts
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/boxarts/

# Option input_remapping_directory
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/remappings/

# Option video_filter_dir
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/video_filters/

# Option audio_filter_dir
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/audio_filters/

# Option dynamic_wallpapers_directory
mkdir -p ${INSTALL_PATH_RETROARCH_STUFF}/wallpapers/

echo "Exit..."
exit 0

# --- Copy PPSSPP assets if PPSSPP core compiled
# See http://wiki.libretro.com/index.php?title=PPSSPP

# --- Copy default config and modify it to match installation ---
echo "Copying Retroarch config file..."
# Never overwrite config it already exists!
cp ./libretro-super/retroarch/retroarch.cfg ${RETROARCH_CFG}

# General configuration
sed -i -e "s/# libretro_path = \"\/path\/to\/libretro.so\"/libretro_path = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# libretro_directory =/libretro_directory = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# libretro_info_path =/libretro_info_path = \"~\/bin\/bin-libretro\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# rgui_browser_directory =/rgui_browser_directory = \"~\/Games\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# core_assets_directory =/core_assets_directory = \"~\/Games\/\"/" ${RETROARCH_CFG}

# Directory configuration
sed -i -e "s/# video_shader_dir =/video_shader_dir = \"~\/bin\/retroarch\/common-shaders\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# overlay_directory =/overlay_directory = \"~\/bin\/retroarch\/overlays\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# osk_overlay_directory =/osk_overlay_directory = \"~\/bin\/retroarch\/overlays\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# assets_directory =/assets_directory = \"~\/bin\/retroarch\/assets\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# joypad_autoconfig_dir =/joypad_autoconfig_dir = \"~\/bin\/retroarch\/joy_autoconfig\/\"/" ${RETROARCH_CFG}

sed -i -e "s/# playlist_directory =/playlist_directory = \"~\/bin\/retroarch\/playlists\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# savefile_directory =/savefile_directory = \"~\/bin\/retroarch\/savefiles\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# savestate_directory =/savestate_directory = \"~\/bin\/retroarch\/savestates\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# system_directory =/system_directory = \"~\/bin\/retroarch\/system\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# screenshot_directory =/screenshot_directory = \"~\/bin\/retroarch\/screenshots\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# boxarts_directory =/boxarts_directory = \"~\/bin\/retroarch\/boxarts\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# input_remapping_directory =/input_remapping_directory = \"~\/bin\/retroarch\/remappings\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_filter_dir =/video_filter_dir = \"~\/bin\/retroarch\/video_filters\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# audio_filter_dir =/audio_filter_dir = \"~\/bin\/retroarch\/audio_filters\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# dynamic_wallpapers_directory =/dynamic_wallpapers_directory = \"~\/bin\/retroarch\/wallpapers\/\"/" ${RETROARCH_CFG}

# Directories already created
sed -i -e "s/# content_database_path =/content_database_path = \"~\/bin\/retroarch\/libretrodb\/rdb\/\"/" ${RETROARCH_CFG}
sed -i -e "s/# cheat_database_path =/cheat_database_path = \"~\/bin\/retroarch\/libretrodb\/cht\/\"/" ${RETROARCH_CFG}
echo "cursor_directory = \"~/bin/retroarch/libretrodb/cursors/\"" >> ${RETROARCH_CFG}

# --- Other options ---
# sed -i -e "s/# menu_driver = \"rgui\"/menu_driver = \"xmb\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_font_path =/video_font_path =\"~\/bin\/retroarch\/assets\/xmb\/monochrome\/font.ttf\"/" ${RETROARCH_CFG}
sed -i -e "s/# video_font_size = 48/video_font_size = 22/" ${RETROARCH_CFG}
sed -i -e "s/# input_max_users = 16/input_max_users = 2/" ${RETROARCH_CFG}
sed -i -e "s/# input_autodetect_enable = true/input_autodetect_enable = true/" ${RETROARCH_CFG}

# * Extra options from Lakka (maybe added in the future)
# sed -i -e "s/# rgui_show_start_screen = true/rgui_show_start_screen = false/" ${RETROARCH_CFG}

# sed -i -e "s/# video_fullscreen = false/video_fullscreen = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_smooth = true/video_smooth = false/" ${RETROARCH_CFG}
# sed -i -e "s/# video_aspect_ratio_auto = false/video_aspect_ratio_auto = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_threaded = false/video_threaded = true/" ${RETROARCH_CFG}
# sed -i -e "s/# video_gpu_screenshot = true/video_gpu_screenshot = false/" ${RETROARCH_CFG}

# sed -i -e "s/# audio_driver =/audio_driver = \"alsathread\"/" ${RETROARCH_CFG}
# sed -i -e "s/# input_driver = sdl/input_driver = udev/" ${RETROARCH_CFG}
# sed -i -e "s/# input_menu_toggle_gamepad_combo =/input_menu_toggle_gamepad_combo = \"2\"/" ${RETROARCH_CFG}

# sed -i -e "s/# menu_core_enable = true/menu_core_enable = false/" ${RETROARCH_CFG}

# echo "playlist_names = \"$RA_PLAYLIST_NAMES\"" >> ${RETROARCH_CFG}
# echo "playlist_cores = \"$RA_PLAYLIST_CORES\"" >> ${RETROARCH_CFG}
